name: Check PR

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write  # needed to post the results comment on PRs
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'
      - run: make test | tee output.txt
      - uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: readFile('output.txt')
            })

  lint:
    name: Lint 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write  # needed to post the results comment on PRs
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'
      - run: make fmt vet | tee output.txt 
      - uses: actions/github-script@v3
        with:
          github-token: ${{ github.token }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: readFile('output.txt')
            })

