name: Check PR

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write  # needed to post the results comment on PRs
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: 'backend/go.mod'
      - run: make test

  lint:
    name: Lint 
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write  # needed to post the results comment on PRs
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-go@v7
        with:
          go-version-file: 'backend/go.mod'
      - run: make fmt vet
